env: chain walk
norm: fro
num_iterations: 30000
search_steps: 30000

get_optimal: True # Get the optimal parameters from the database
compute_optimal: True # Run a grid search. When recompute_optimal is false, we don't run a grid search if the optimal parameters are in the database already
recompute_optimal: False # If compute_optimal is True, run a grid search even if the optimal parameters are in the database
debug: False # If multiprocessing should be disabled

agent_name: diagonal semi gradient Q updater

meta_lr: 1e-4
meta_lr_p: -1
meta_lr_I: -1
meta_lr_d: -1
lambda: 0
delay: 1
alpha: 0.01
beta: 0.99
epsilon: 0.1
measure_time: False

follow_trajectory: False
log_plot: False
plot_updater: True
stop_if_diverging: False
normalize: True
repeat: 1

kp: 1
ki: 0
kd: 0

gamma: 0.999

name: fine-tuning
save_dir: ${oc.env:OUTPUT_DIR,./outputs}/${hydra.job.config_name}/${name}/${env}/${now:%Y-%m-%d}/${now:%H-%M-%S}

seed: -1
hydra:
  run:
    dir: ${oc.env:OUTPUT_DIR,./outputs}/${hydra.job.config_name}/${name}/${env}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: False