env: chain walk
norm: 1
num_iterations: 30000

agent_name: diagonal sampler
get_optimal: False
meta_lr: 0.01

gamma: 0.999

seed: -1
hydra:
  run:
    dir: ${oc.env:OUTPUT_DIR,./outputs}/${hydra.job.config_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: True