env: garnet 314 50
norm: 1
num_iterations: 30000

get_optimal: True # Get the optimal parameters from the database
compute_optimal: False # Run a grid search. When recompute_optimal is false, we don't run a grid search if the optimal parameters are in the database already
recompute_optimal: False # If compute_optimal is True, run a grid search even if the optimal parameters are in the database

agent_name: [semi gradient updater, semi gradient updater, semi gradient updater, semi gradient updater]
meta_lr: [1e-4, 2e-4, 3e-4, 4e-4]
delay: [500, 500, 500, 500]
lambda: [1e-3, 1e-3, 1e-3, 1e-3]

follow_trajectory: False
log_plot: True

kp: 1
ki: 0
kd: 0
alpha: 0.05
beta: 0.95

gamma: 0.99

name: presentation compiler

seed: 42
hydra:
  run:
    dir: ${oc.env:OUTPUT_DIR,./outputs}/${hydra.job.config_name}/${name}/${env}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: True