env: cliff walk
norm: 1
num_iterations: 100000

get_optimal: False

agent_name: [true cost]
meta_lr: [1e-10, 1e-12, 1e-13, 1e-10]
delay: [10, 1, 1, 1]

follow_trajectory: False

kp: 1
ki: 0
kd: 0
alpha: 0.05
beta: 0.95

gamma: 0.9999

name: cliff walk solver

seed: 66784
hydra:
  run:
    dir: ${oc.env:OUTPUT_DIR,./outputs}/${hydra.job.config_name}/${name}/${env}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: True