env: chain walk
norm: 1
num_iterations: 10000

get_optimal: False

agent_name: [true cost, diagonal log space updater]  # [diagonal sampler, diagonal sampler, diagonal sampler]
meta_lr: [1e-3, 0.2, 1e-5]
delay: [1, 1, 1]

follow_trajectory: False

kp: 1
ki: 0
kd: 0
alpha: 0.05
beta: 0.95

gamma: 0.9999

seed: 1234343
hydra:
  run:
    dir: ${oc.env:OUTPUT_DIR,./outputs}/${hydra.job.config_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: True