env: chain walk  # 'chain walk' or 'garnet'
norm: 1
num_iterations: 5000
meta_lr: 0.3
sample_size: 100

alpha_P: 0.05
N_P: 1000
alpha_D: 0.9
N_D: 1000
alpha_I: 0.9
N_I: 1000

debug: True  # If true, don't estimate the gradients
planning: False  # Reproduce PID-VI paper

seed: -1
hydra:
  run:
    dir: ${oc.env:OUTPUT_DIR,./outputs}/${hydra.job.config_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: True