kp: [1, 1, 1, 1]  # 1.2
kd: [0.4, 0, 0.4, 0.2]  # 0
ki: [0, 0.75, 0.75, 0.7]  # 0

seed: -1
hydra:
  run:
    dir: ${oc.env:OUTPUT_DIR,./outputs}/${hydra.job.config_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: True