kp: [1, 1.1, 1, 1]
kd: [0.5, 0, 0.15, 0.2]
ki: [0, 0, 0, -0.4]

seed: -1
hydra:
  run:
    dir: ${oc.env:OUTPUT_DIR,./outputs}/${hydra.job.config_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: True