kp: [1, 0.9, 1, 1] # [1, 1.1, 1, 1, 1, 1, 1]
kd: [0, 0, 0, 0.15] # [0, 0, 0.15, 0, 0.3, 0.15, 0.3]
ki: [0, 0, -0.4, 0] # [0, 0, 0, -0.4, 0, -0.4, -0.2]
alpha: [0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05]
beta: [0.95, 0.95, 0.95, 0.95, 0.95, 0.95, 0.95]
gamma: 0.99

env: chain walk

norm: 1
num_iterations: 500
normalize: True

seed: -1
hydra:
  run:
    dir: ${oc.env:OUTPUT_DIR,./outputs}/${hydra.job.config_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: True