kp: [1, 1, 1, 1, 1]
kd: [0, 0, 0.4, 0.4, 0.2]
ki: [0, 0.75, 0, 0.75, 0.7]
alpha: [0.05, 0.05, 0.05, 0.05, 0.05]
beta: [0.95, 0.95, 0.95, 0.95, 0.95]

gamma: 0.99
env: chain walk

norm: fro   # fro or nuc
num_iterations: 1000
normalize: False

seed: -1
hydra:
  run:
    dir: ${oc.env:OUTPUT_DIR,./outputs}/${hydra.job.config_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: True