kp: [1, 1, 1]
kd: [0.4, 0, 0.2]

N: 100
alpha: 0.03
gamma: 0.99
num_iterations: 1000

norm: 1
env: chain walk

follow_trajectory: False

seed: -1
hydra:
  run:
    dir: ${oc.env:OUTPUT_DIR,./outputs}/${hydra.job.config_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: True