kp: [1, 1, 1]
kd: [0.4, 0, 0.2]

N: 100
alpha: 0.03

norm: 1
env: chain walk

seed: -1
hydra:
  run:
    dir: ${oc.env:OUTPUT_DIR,./outputs}/${hydra.job.config_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: True