kp: [1]
kd: [0.05]
ki: [0]
alpha: [0.05]
beta: [0.95]
delays: [1, 5, 10]

num_iterations: 10000
norm: 1
env: chain walk
gamma: 0.99

follow_trajectory: False
get_optimal: False

seed: -1
hydra:
  run:
    dir: ${oc.env:OUTPUT_DIR,./outputs}/${hydra.job.config_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: True