kp: [1, 1, 1]
kd: [0.1, 0.2, 0.3]
ki: [0, 0, 0]
delays: [1, 5, 10]

num_iterations: 5000

learning_rates: {0.1: {1, 10, 100}, 0.05: {1, 10, 100}, 0.01: {1, 10, 100}}

seed: -1
hydra:
  run:
    dir: ${oc.env:OUTPUT_DIR,./outputs}/${hydra.job.config_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: True