kp: [1, 1, 1, 1]
kd: [0, 0.4, 0.49, 0.5]
ki: [0, 0, 0, 0]
alpha: [0.05, 0.05, 0.05, 0.05]
beta: [0.95, 0.95, 0.95, 0.95]
gamma: 0.02

env: identity
num_iterations: 10000
norm: 1
get_optimal: False

seed: -1
hydra:
  run:
    dir: ${oc.env:OUTPUT_DIR,./outputs}/${hydra.job.config_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: True