kp: [1, 1, 1, 1]
kd: [0.4, 0, 0.4, 0.2]
ki: [0, 0.75, 0.75, 0.7]

N: 100
alpha: 0.03
update_alpha: 0.03
update_N: 100


hydra:
  run:
    dir: ${oc.env:OUTPUT_DIR,./outputs}/${hydra.job.config_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: True