kp: 1
kd: 0
ki: 0
alpha: 0.05
beta: 0.95
gamma: 0.99

type: polynomial

env: CartPole-v1
num_iterations: 30000
norm: 1
get_optimal: False # Get the optimal parameters from the database
compute_optimal: False # Run a grid search. When recompute_optimal is false, we don't run a grid search if the optimal parameters are in the database already
recompute_optimal: False # If compute_optimal is True, run a grid search even if the optimal parameters are in the database
repeat: 3
order: 10

follow_trajectory: False
stop_if_diverging: False
log_plot: False
normalize: True
search_steps: 1000

save_dir: ${oc.env:OUTPUT_DIR,./outputs}/${hydra.job.config_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

seed: 2388
hydra:
  run:
    dir: ${oc.env:OUTPUT_DIR,./outputs}/${hydra.job.config_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: False