kp: [1, 1, 1, 1, 1, 1]
kd: [0, 0.1, 0.2, 0.3, 0.4, 0.5]
ki: [0, 0, 0, 0, 0, 0]
alpha: [0.05, 0.05, 0.05, 0.05, 0.05, 0.05]
beta: [0.95, 0.95, 0.95, 0.95, 0.95, 0.95]
gamma: 0.99

optimizer: [Adam, Adam, Adam, Adam, Adam, Adam]
replay_memory_size: [1000000, 1000000, 1000000, 1000000, 1000000, 1000000]
batch_size: [64, 64, 64, 64, 64, 64]
learning_rate: [1e-4, 1e-4, 1e-4, 1e-4, 1e-4, 1e-4]
epsilon: [1, 1, 1, 1, 1, 1]
epsilon_decay: [0.999, 0.999, 0.999, 0.999, 0.999, 0.999]
epsilon_min: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
epsilon_decay_step: [1, 1, 1, 1, 1, 1]
train_step: [2, 2, 2, 2, 2, 2]
tau: [0.005, 0.005, 0.005, 0.005, 0.005, 0.005]

num_episodes: 300
num_iterations: 10000
norm: 1
normalize: True

follow_trajectory: False

env: CartPole-v1
use_episodes: True

seed: -1
hydra:
  run:
    dir: ${oc.env:OUTPUT_DIR,./outputs}/${hydra.job.config_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: True