kp: [1, 1, 1]
kd: [0.0, 0.1, 0.2]
ki: [0, -0.2, 0]
alpha: [0.05, 0.05, 0.05]
beta: [0.95, 0.95, 0.95]
gamma: 0.99

optimzer: [Adam, Adam, Adam]
replay_memory_size: [10000, 10000, 10000]
batch_size: [32, 32, 32]
learning_rate: [1e-2, 1e-2, 1e-2]
target_net_update_steps: [100, 100, 100]
epsilon: [1, 1, 1]
epsilon_decay: [0.9999, 0.9999, 0.9999]
epsilon_min: [0.01, 0.01, 0.01]
epsilon_decay_step: [10, 10, 10]
train_step: [100, 100, 100]

get_optimal: False

isSoft: True
num_iterations: 20000
norm: 1
normalize: True

follow_trajectory: False

env: CartPole-v0

seed: -1
hydra:
  run:
    dir: ${oc.env:OUTPUT_DIR,./outputs}/${hydra.job.config_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: True