kp: [1, 1, 1, 1]
kd: [0, 0, 0.1, 0.1]
ki: [0, -0.4, 0, -0.15]

threshold: 0
num_iterations: 3000

seed: -1
hydra:
  run:
    dir: ${oc.env:OUTPUT_DIR,./outputs}/${hydra.job.config_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: True