kp: [1, 1, 1]
kd: [0.1, 0.2, 0.3]
ki: [0, 0, 0]

num_iterations: 10000
isSoft: True
norm: 1

env: garnet  # Set this to 'chain walk' or 'garnet'

learning_rates: {}
update_rates: {}

seed: -1
hydra:
  run:
    dir: ${oc.env:OUTPUT_DIR,./outputs}/${hydra.job.config_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: True