atari:
  env: AtlantisNoFrameskip-v4
  optimizer: Adam
  replay_memory_size: 100000
  batch_size: 32
  learning_rate: 1e-4
  initial_eps: 1
  exploration_fraction: 0.5
  minimum_eps: 0.01
  gradient_steps: 1
  train_freq: 4
  target_update_interval: 1000
  tau: 1
  inner_size: 256
  learning_starts: 100000
  num_iterations: 2000000
  gamma: 0.99
  target_reward: 100