cartpole:
  env: CartPole-v1
  optimizer: Adam
  replay_memory_size: 100000
  batch_size: 64
  learning_rate: 0.0023
  initial_eps: 1
  exploration_fraction: 0.16
  minimum_eps: 0.04
  gradient_steps: 128
  train_freq: 256
  target_update_interval: 250  # 10
  tau: 1
  inner_size: 256
  learning_starts: 1000
  num_iterations: 50000
  gamma: 0.99
  target_reward: 195