lunarlander:
  env: LunarLander-v2
  optimizer: Adam
  replay_memory_size: 50000
  batch_size: 128
  learning_rate: 6.3e-4
  initial_eps: 1
  exploration_fraction: 0.12
  minimum_eps: 0.1
  gradient_steps: -1
  train_freq: 4
  target_update_interval: 250
  tau: 1
  inner_size: 256
  learning_starts: 0
  num_iterations: 100000
  gamma: 0.99
  target_reward: 200