mountaincar:
  env: MountainCar-v0
  optimizer: Adam
  replay_memory_size: 50000
  batch_size: 128
  learning_rate: 4e-3
  initial_eps: 1
  exploration_fraction: 0.2
  minimum_eps: 0.07
  gradient_steps: 8
  train_freq: 16
  target_update_interval: 600
  tau: 1
  inner_size: 256
  learning_starts: 1000
  num_iterations: 600 # Steps: 120000
  gamma: 0.98