atari:
  env: PongNoFrameskip-v4
  optimizer: Adam
  replay_memory_size: 400000
  batch_size: 32
  learning_rate: 1e-4
  initial_eps: 1
  exploration_fraction: 0.4  # Modified exploration fraction for the reduced number of iterations
  minimum_eps: 0.01
  gradient_steps: 1
  train_freq: 4
  target_update_interval: 1000
  tau: 1
  inner_size: 256
  learning_starts: 100000
  num_iterations: 2500000
  gamma: 0.99