num_iterations: 5000
type: Adagrad

# Adam Parameters
beta1: 0.9
beta2: 0.999
epsilon: 0.000000001
# ka: 0.001

gamma: 0.99
# Adagrad Paramaters
ka: 3

follow_trajectory: False
normalize: True

learning_rates: {}
update_D_rates: {}
update_I_rates: {}

norm: 1
env: chain walk

seed: -1
hydra:
  run:
    dir: ${oc.env:OUTPUT_DIR,./outputs}/${hydra.job.config_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: True